name: CD

on:
  push:
    branches:
    - release/**
  pull_request:
    branches:
    - release/**
    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: './Solution/Modules.sln'

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Get Build Version
      run: |
        Get-ChildItem
        Import-Module Solution\Tools\GetBuildVersion.psm1
        Write-Host $env:GITHUB_REF
        $version = GetBuildVersion -VersionString $env:GITHUB_REF
        echo "BUILD_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append
      shell: pwsh

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 5.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore dependencies
      run: nuget restore $env:SOLUTION

    - name: Build
      run: dotnet build $env:SOLUTION --configuration $env:BUILD_CONFIG -p:Version=$env:$BUILD_VERSION --no-restore

    - name: Run tests
      run: dotnet test $env:SOLUTION /p:Configuration=$env:BUILD_CONFIG --no-restore --no-build --verbosity normal
      
    - name: Publish
      if: startsWith(github.ref, 'refs/heads/release')
      run: |
        nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
        nuget push **\*.nupkg -Source 'https://nuget.pkg.github.com/joshika39/index.json' --api-key ${{secrets.GIT_API_KEY}}